### ISSUE TITLE
Compilation is fine but after upload to m5stack core screen remains black no response on buttons

### ISSUE THREAD

**Issue by MrBambix** [armel/DXTracker#30]
Hi,

Just came across your project and looks great. Loaded it into PlatformIO on VSCode ok and compilation went fine without errors. I then uploaded it to my M5Stack Core and upload went fine but after the uploade the screen remains black and the buttons have no response either. Any ideas would be great, I have uploaded several other programs to my M5Stack core so it is fine.

thanks,
Leo

**Comment by MrBambix** [comment]
Hi Armel,
My M5Stack is the Core version, witht the three physical buttons, i did just found out it is a 4mb version though. I did actually change the settings in those two files to basic.

thank you for responding so quickly

regards,
leo

**Comment by armel** [comment]
Ok I haven't got any 4 mb version. So,

In DXTracker.h, line 5, you must have : 

#define BOARD BASIC

And, in plateformio.ini, line 12 and 13 :

default_envs = m5stack-basic-grey
;default_envs = m5stack-core2

Try eventually to comment line 40 in plateformio.ini, so add a comma at the beginning : 

;board_build.partitions = large_spiffs_16MB.csv

Armel.

**Comment by MrBambix** [comment]
Hi Armel,

Well i actually modified the platformIO.ini to be:

[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
lib_deps = 
	m5stack/M5Stack@^0.4.0
	bodmer/JPEGDecoder@^1.8.1
	tobozo/M5Stack-SD-Updater@^1.2.0

then it is fine so all working great now,

Thanks, 
Leo

**Comment by MrBambix** [comment]
HI Armel,
Yes for sure thank you for this great idea and implementation!
regards,
Leo
